{% set version = "1.1.0" %}
{% if 1 %}{% set jupyterlab = "jupyterlab >=4.2.0,<5" %}{% endif %}

package:
  name: jupyter-docprovider
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyter-docprovider/jupyter_docprovider-{{ version }}.tar.gz
  sha256: c2ddc8d9a82329fff0a95261cc827b669359876af7fb2f2bafa8dbdf839ab172

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  number: 0

requirements:
  host:
    - {{ jupyterlab }}
    - hatch-jupyter-builder
    - hatchling >=1.4.0
    - pip
    - python >=3.8
  run:
    - python >=3.8
  run_constrained:
    - {{ jupyterlab }}

test:
  requires:
    - pip
    - jupyterlab
    - m2-grep  # [win]
  imports:
    - jupyter_docprovider
  commands:
    - pip check
    # labextensions
    - jupyter labextension list
    # check
    - jupyter labextension list 1>labextensions 2>&1
    - grep -iE "docprovider-extension.*OK" labextensions


about:
  home: https://github.com/jupyterlab/jupyter-collaboration
  summary: JupyterLab/Jupyter Notebook 7+ extension integrating collaborative shared models.
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - jupyter_docprovider/labextension/static/third-party-licenses.json
  doc_url: https://jupyterlab-realtime-collaboration.readthedocs.io

extra:
  recipe-maintainers:
    - conda-forge/jupyter-collaboration
    - bollwyvl
    # TODO: uncommment as PR #1 on feedstock
    # - conda-forge/jupyter-collaboration
